services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"

    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: SnapExpense
  ai-service:
    build:
      context: ./services/ai-service
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      FLAGS_use_mkldnn: "0"
      FLAGS_enable_pir_in_executor: "0"
